#ifndef STEELPATCHER_RECORDED_MACRO_PATCH_ABI_H_
#define STEELPATCHER_RECORDED_MACRO_PATCH_ABI_H_

#define PATCH_HEADER_SIZE 0x48
#define PATCH_ABI_VERSION 1
#define PATCH_HEADER_ABI ((PATCH_ABI_VERSION << 16) | PATCH_HEADER_SIZE)
#define PATCH_PRESS_ENTRY_OFFSET 0x2C
#define PATCH_RELEASE_ENTRY_OFFSET 0x30
#define PATCH_TICK_ENTRY_OFFSET 0x34
#define PATCH_ERASE_ENTRY_OFFSET 0x38
#define PATCH_PUSH_ENTRY_OFFSET 0x3C
#define PATCH_PULL_ENTRY_OFFSET 0x40

#endif
